name: "flat-manager"
description: "Deploy your Flatpak application to a repository"
author: "Bilal Elmoussaoui"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  repository:
    description: >
      The Flatpak repository to push the build into.
    required: true
  flat-manager-url:
    description: >
      The flat-manager repository URL.
    required: true
  token:
    description: >
      A flat-manager token to publish into the repository
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
