on: [push, pull_request]
name: Flatpak
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bilelmoussaoui/flatpak-github-actions@wip
      with:
        bundle: "palette.flatpak"
        manifest: "org.gnome.zbrown.Palette.yml"
        app-id: "org.gnome.zbrown.Palette"
        runtime-repo: "https://flathub.org/repo/flathub.flatpakrepo"
