on: [push, pull_request]
name: Flatpak
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        manifest-path: org.example.MyApp.yaml
        flatpak-module: testproject
        app-id: org.example.MyApp.Devel
        bundle: org.example.MyApp.Devel.flatpak
        runtime-repo: https://flathub.org/repo/flathub.flatpakrepo
