on:
  push:
  # branches: [master]
  pull_request:

name: CI
jobs:
  flatpak-builder:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - uses: ./flatpak-builder
        with:
          bundle: org.example.MyApp.Devel.flatpak
          manifest-path: ./flatpak-builder/tests/test-project/org.example.MyApp.yaml
          cache-key: flatpak-builder-${{ github.sha }}
      - uses: ./flat-manager
        with:
          repository: elementary
          flat-manager-url: https://flatpak-api.elementary.io
          token: some_very_hidden_token

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --also=dev
        working-directory: flatpak-builder
      - run: npm test
        working-directory: flatpak-builder
