on:
  push:
    branches: [master]
  pull_request:

name: CI
jobs:
  flatpak-builder:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - uses: bilelmoussaoui/flatpak-github-actions@tests
        with:
          bundle: org.example.MyApp.Devel.flatpak
          manifest-path: org.example.MyApp.yaml
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --also=dev
      - run: npm test