on: [push, pull_request]
name: Lint
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker://bilelmoussaoui/flatpak-builder-github-actions
      with:
        args: --manifest-path="org.gnome.zbrown.Palette.yaml" --app-id "org.gnome.zbrown.Palette" --bundle "palette-nightly.flatpak"