on: [push, pull_request]
name: Flatpak
jobs:
  flatpak-builder:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Pull the Docker Image
      run: docker pull bilelmoussaoui/flatpak-github-actions:latest
    - name: Run Docker Image
      run: |
            docker run --cap-add SYS_ADMIN --device /dev/fuse \
              -v "/var/run/docker.sock":"/var/run/docker.sock" \
              -v "/home/runner/work/_temp/_github_home":"/github/home" \
              -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
              -v ${{ github.workspace }}:"/github/workspace" \
              bilelmoussaoui/flatpak-github-actions:latest \
              --manifest-path "org.gnome.zbrown.Palette.yaml" \
              --app-id "org.gnome.zbrown.Palette" \
              --bundle "palette-nightly.flatpak"
